### PR TITLE
revert previous commit

### PR DESCRIPTION
**Pull request by ultrasaurus**
0.10.6 worked for me (though failed for @rogeruiz in production)
this commit makes dev work for me again

can anyone else test and provide another pair of eyes?

### CODE REVIEW

**Comment by DavidEBest** [comment]
I see the same thing.

`dev` reports: 
`Uncaught TypeError: $.widget is not a function(anonymous function) @ jquery.fileupload.js:62...`

when I run it locally with `npm run watch --prod`.

This pr, `revert` loads the site correctly.

What was the issue @rogeruiz was seeing in production with `0.10.6`?

**Comment by ultrasaurus** [comment]
@DavidEBest there was an error building from browserify
```
2016-06-10T15:02:13.72-0400 [App/1]      ERR Error: module not found: "jquery" from file /home/vcap/app/assets/js/backbone/app.js
2016-06-10T15:02:13.74-0400 [App/1]      ERR npm ERR! node v4.4.5
2016-06-10T15:02:13.74-0400 [App/1]      ERR npm ERR! npm  v3.8.9
2016-06-10T15:02:13.74-0400 [App/1]      ERR npm ERR! code ELIFECYCLE
2016-06-10T15:02:13.74-0400 [App/1]      ERR npm ERR! openopps-platform@0.10.5 browserify: `browserify assets/js/backbone/app.js -o assets/js/bundle.js -t [ babelify --presets [ es2015 stage-0 ] ] -t [ brfs ]`
2016-06-10T15:02:13.74-0400 [App/1]      ERR npm ERR! Exit status 1
```

**Comment by ultrasaurus** [comment]
I was running with an older (2.x) version of npm, just upgraded and test v0.10.6 with npm 3.9.5 and that works fine for me too.

**Comment by ultrasaurus** [comment]
since @DavidEBest confirmed that `dev` doesn't work for him, and this commit does, I will merge

**Pull request merged**
