### PR TITLE
[WIP] As a user, want to be able to see on a participant's profile page all the tasks they are assigned or have completed.

### PR DESCRIPTION
**Pull request by jmduke**
Blank PR (for now) for https://micropurchase.18f.gov/auctions/43.

### CODE REVIEW

**Comment by mtorres253** [comment]
Hi @jmduke let us know if you have any questions. When you're ready for us to review the code, just go to the auction page https://micropurchase.18f.gov/auctions/43 and click the "I'm done" button. Remember that the delivery deadline is tomorrow at 1:00 ET

**Comment by jmduke** [comment]
Hi @mtorres253 -- the deadline listed on the auction site is on the 28th, not the 26th (see: https://micropurchase.18f.gov/auctions/43).  Could you please clarify if that is the correct date or not?

**Comment by mtorres253** [comment]
Sorry Justin you are correct! Copy paste error.

**Comment by rogeruiz** [comment]
Closing this since it looks like there's no more commits coming here. Feel free to open it up if I'm wrong though. 👍

**Pull request closed without merging**
