### PR TITLE
[WIP] Dockerfile for aws

### PR DESCRIPTION
**Pull request by ultrasaurus**
Work-in-progress PR -- Dockerfile and documentation for deploying on AWS so that we can set up an dev server for open source contributors to access: https://github.com/openopps/openopps-platform/issues/1560

  - ElasticBeanstalk deploys from root Dockerfile
  - created docs/deployments to keep notes on how we deploy OpenOpps
  - checked in package-lock.json (then local and remote deploys match)
  - don’t check in .elasticbeanstalk/* -- this is for local config when using eb cli
  
TO DO:
  - test to see if local docker setup works with docker-compose (I added a CMD to run the node app, not sure how that should work with docker-compose)
  - put npm preinstall back or fix https://github.com/openopps/openopps-platform/issues/1744
  - more docs

To integrate this, I think we probably need to do the following:
- shared config for app and running migrate, init, demo:
   - migrate: https://github.com/openopps/openopps-platform/issues/1737
   - demo: https://github.com/openopps/openopps-platform/issues/1739
- database config refactor: https://github.com/openopps/openopps-platform/issues/1740
- package-lock.json: open question https://github.com/openopps/openopps-platform/issues/1742

### CODE REVIEW

**Comment by ultrasaurus** [comment]
@bmcorum would like your thoughts on the approach here.  Now that I've gotten something working, I'd love some feedback on the approach.  Feel free to mark any of the issues I've tagged here as "Help Wanted" and/or suggest ideas on the specific issues or here!

**Comment by bmcorum** [comment]
@ultrasaurus, I understand the usefulness of the package-lock.json, however this little thing can cause a merging nightmare. I removed it from source control recently and added it to the git ignore file. I would hope that for deployments we would run a final install, build and run locally on the machine that will initiate the deploy thus building the newest package-lock.json. Thoughts? Or experience in dealing with the package-lock.json and possible merge conflicts.

**Comment by ultrasaurus** [comment]
@bmcorum thanks for your note -- I've continued the conversation about the lock file in https://github.com/openopps/openopps-platform/issues/1742

for the community dev server, I'd be totally open to using yarn and checking in yarn.lock, even if you don't decide to use it -- I should have thought of that from the start!

If you like my yarn proposal in https://github.com/openopps/openopps-platform/issues/1742 -- I'd be happy to write up notes about it in for our docs and update INSTALL.md, etc., just leave me a note and mark anything "help wanted" if you think it is ready for action.  

Meanwhile I've got plenty to do to create a reproducible build with this branch :)

**Comment by bmcorum** [comment]
@ultrasaurus, the changes you have made to the db/index.js file have re-declared the variable config thus making the first declaration pointless and unusable. It appears as though you have adjusted the code to no longer run locally unless a user creates new environment variables for HOST, DB, USERNAME, PASSWORD, and PORT. Also, you have hardcoded the database name rather than having it passed as an environment variable like the rest of the database connection parameters.

**Comment by ultrasaurus** [comment]
@bmcorum sorry I wasn't clear in my original note when I submitted this WIP PR -- this PR was a "spike" and I hard-coded some stuff just to get it to work holistically and understand the system.  Then I opened a bunch of issues so we could discuss different potential changes that would make it easier to deploy straight on AWS while still supporting the federal Cloud Foundry (cloud.gov) deployment

**Comment by bmcorum** [comment]
In the future please reserve pull request for completed code that is tested and ready to be merged.

**Pull request closed without merging**
