### PR TITLE
updating the badges to openopps repos

### PR DESCRIPTION
**Pull request by DavidEBest**

### CODE REVIEW

**Comment by ultrasaurus** [comment]
hmmm... when I view the file I get a broken image:
image

shouldn't that work?

**Comment by DavidEBest** [comment]
It should. For some reason, the link Circle.ci provides doesn't work within github. Not sure why, yet:
screen shot 2016-06-02 at 6 40 12 am

**Comment by DavidEBest** [comment]
This is fixed. I didn't realize that an API token was required for public projects.

**Comment by ultrasaurus** [comment]
looks good!

**Pull request merged**
