### PR TITLE
[WIP] When there are NO OPEN Agency (GSA) opportunities, user DOES NOT see Agency (GSA) only opportunities section on the dashboard

### PR DESCRIPTION
**Pull request by jmduke**
Re: #1485

### CODE REVIEW

**Comment by jmduke** [comment]
Hi all!  Excited to work on this.  A couple questions:

1.  The spec references a maximum of 3 tasks to be displayed:

> Then I should see the three most recent open opportunities in as section labeled "GSA Opportunities" And I should see a link below that section labeled "See all open GSA opportunities"

Is that logic in the scope of this deliverable, or already implemented?

2. I'm having trouble getting the actual tasks to appear in the dashboard of a test user, even when the Agency matches.  Is there a flag I'm missing?

**Comment by mtorres253** [comment]
Hi @jmduke! Thanks for the questions. I'll defer to @EricSchles who is going to be managing the pull request for this auction. The limit of three opportunities has not yet been implemented and is part of this scope. I defer to Eric for your question about the flag.

**Comment by mtorres253** [comment]
Hi @jmduke let us know if you still have questions @EricSchles

**Comment by jmduke** [comment]
Hey Michael! Thanks -- still waiting to hear back from @EricSchles re: my second question.

**Comment by mtorres253** [comment]
Hi @jmduke let us know if you have any questions. When you're ready for us to review the code, just go to the auction page https://micropurchase.18f.gov/auctions/41 and click the "I'm done" button. Remember that the delivery deadline is tomorrow at 1:00 ET

**Comment by jmduke** [comment]
Hey all, I'm having some issues with my dev environment -- neither `npm run watch` nor `npm server` is correctly serving new assets and the Docker instructions listed in the repo appear to be broken.  Unfortunately, I'm going to miss the deliverable here -- my apologies!

**Pull request closed without merging**
