### PR TITLE
Correct grammatical error in template.html

### PR DESCRIPTION
**Pull request by acolter**
Minor grammar correction in the email that gets sent when you save a draft opportunity.

### CODE REVIEW

**Comment by DavidEBest** [comment]
👍

**Comment by rogeruiz** [comment]
Looks like this PR was opened against `master`. I cherry-picked it to `dev` so we can keep within our Git flow. As a reminder, please make sure that all patches are submitted against the `dev` branch unless they are specifically trying to bypass our Git flow for the repository. Thanks!

**Comment by acolter** [comment]
Got it. Will submit against the dev branch from now on.

**Comment by DavidEBest** [comment]
D'oh! Sorry about that, @rogeruiz! Guess I got a little trigger happy.

**Comment by rogeruiz** [comment]
@acolter @DavidEBest No need and no worries. I've cherry-picked and pushed it up to `dev` 💃 👍

**Pull request merged**
